### ISSUE TITLE
PrivacyBrowser crash on start

### ISSUE THREAD

**Issue by foresto** [derfelot/discussion#18] opened 2017-09-09 21:46 UTC
I just updated from a 20170526 build to 20170909. I see the default Browser has been replaced with PrivacyBrowser, which crashes when attempting to start it. Clearing the app's cache and data does not help.

logcat here:

https://gist.github.com/anonymous/0167f7e4c2c1c4da6cc53145ad82da52

**Comment by MSe1969** [comment] 2017-09-10 09:56
Hi, I have followed the conversation with Soren Stoutner on XDA and as stated, it works fine on my device. Nevertheless, I'm currently doing a clean build and check again, just to make sure.

**Comment by MSe1969** [comment] 2017-09-10 20:17
Hi, 
I can't reproduce what you describe. Even after doing an explicit clean build (I did a clean build before, but to update the browser prebuilt, I indeed simply rebuilt and did not an own clean build), I can only repeat, what I said already before - Privacy Browser works without any issues.
I haven't received any further complaints from other users. Further, based on your conversation with Soren Stoutner in the respective XDA thread of this ROM, the app crashes in your environment / on your device even when you download it from F-Droid.
From the log, it seems that there is some issue loading webview (which is needed by Privacy-Browser).
`Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>` 
Maybe clearing the webview app data could help? 

Further, I have noticed you use a CM theme (com.ngocgiap.ficolordark) - does the crash also happen when you use the default theme? There normally is nothing wrong in using themes, but worth a try to narrow down the issue.

Anyways, there is nothing what we can do with regards to correcting anything in our build, therefore I will close this issue. (You can still comment on it also in closed state and I'll be happy to re-open it, if there is evidence of an issue with the build)

Kind regards, M.

**Closed by MSe1969** 2017-09-10 20:17 UTC

**Comment by foresto** [comment] 2017-09-11 19:01
Mystery solved: The problem is apparently triggered when Privacy Browser is started for the first time with a non-default theme applied in the "Style" category.

Workaround: Apply the default Style in the LineageOS Theme Chooser, start Privacy Browser, and then switch back to the Style of choice.

Thanks for the hint, @MSe1969
